AICP_BRANCH=r

# AICP RELEASE VERSION
AICP_VERSION_MAJOR = 16
AICP_VERSION_MINOR = 1
AICP_VERSION_MAINTENANCE = 0

PRODUCT_VERSION_MAJOR := $(AICP_VERSION_MAJOR)
PRODUCT_VERSION_MINOR := $(AICP_VERSION_MINOR)
PRODUCT_VERSION_MAINTENANCE := $(AICP_VERSION_MAINTENANCE)

VERSION := $(AICP_VERSION_MAJOR).$(AICP_VERSION_MINOR)

#We reset back to UNOFFICIAL
AICP_VERSION := $(TARGET_PRODUCT)_$(AICP_BRANCH)-$(VERSION)-UNOFFICIAL-$(shell date -u +%Y%m%d)
